version: "3"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  _python_base_image_build:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: streamlit-playground-base
    command: ["echo", "build completed"]

  streamlit:
    image: streamlit-playground-base
    container_name: streamlit-app-dev
    ports:
      - "8501:8501"
    volumes:
      - ".:/app"
    entrypoint: ["streamlit", "run", "Home.py"]
    networks:
      - streamlit-playground

networks:
  streamlit-playground:
    driver: bridge

volumes:
  db:
    driver: local
